### ISSUE TITLE
Publish Docker Image to ghcr.io

### ISSUE THREAD

**Issue by kangaechu** [enechange/collmbo#6]
Hello, thank you for this wonderful project.

I noticed that this repository includes a Dockerfile, allowing for local builds, but there doesn't appear to be an official Docker image published to ghcr.io. Publishing an official Docker image to ghcr.io would provide several benefits:

1. Improved User Convenience: Users can easily pull and use the Docker image without needing to build it locally.
2. Consistency: An official Docker image ensures consistent environments for all users.
3. Simplified Deployment: Using an official image simplifies the setup of CI/CD pipelines.

If you need any assistance, please let me know. Thank you for considering this request.

**Comment by iwamot** [comment]
@kangaechu Thank you for your excellent suggestions! I will publish the Docker images in the near future.

**Comment by iwamot** [comment]
Hi @kangaechu, sorry for the wait, but I've finally got the image publishing workflow up and running.

- https://github.com/iwamot/collmbo/pull/9

You can now use the following images:

- ghcr.io/iwamot/collmbo:latest-full
- ghcr.io/iwamot/collmbo:N.N.N-full
- ghcr.io/iwamot/collmbo:latest-slim
- ghcr.io/iwamot/collmbo:N.N.N-slim

Thanks again for the great suggestion!
